# -*- coding: utf-8 -*-
"""Train_Test_Split--Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ior6cZa_ZYPgATMMiDJn3u5DzGDZCuZ
"""

#Attrition data convert categorial to numerical and the train_test_split
import numpy as np
import pandas as pd

df = pd.read_csv("/content/Attrition - Attrition.csv")
df.head(10)

df['Attrition'].value_counts()
df['BusinessTravel'].value_counts()
df['Department'].value_counts()
df['EducationField'].value_counts()

df['Attrition']=df['Attrition'].map({'Yes':0, 'No':1})
df['BusinessTravel']=df['BusinessTravel'].map({'Travel_Rarely':0, 'Travel_Frequently':1, 'Non-Travel':2})
df['Department']=df['Department'].map({'Research & Development':0, 'Sales':1, 'Human Resources':2 })
df['EducationField']=df['EducationField'].map({'Life Sciences':0, 'Medical':1, 'Marketing':2, 'Technical Degree':3, 'Other':4, 'Human Resources':5 })

df.isna().sum()

df.shape

x=df.drop(columns = ['Attrition'])
x.shape

y=df['Attrition']
y.shape

from sklearn.model_selection import train_test_split

x_train, x_test,y_train , y_test = train_test_split(x,
                                                    y,
                                                    test_size = 0.2,
                                                    random_state = 52)

print("Total shape of df :", df.shape)
print('-------------------------------')
print("independent data shape :", x.shape)
print("x_train data shape :", x_train.shape)
print("x_test data shape :",x_test.shape)
print("--------------------------------")
print("Target data shape :", y.shape)
print("y_train data shape :",y_train.shape)
print("y_test data shape :",y_test.shape)
print("---------------------------------")

df